spring:
  application:
    name: authorization-service

server:
  port: 8083

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true


online-learning:
  oauth2:
    clients:
      - clientId: online-learning-web
        password: 1234
        accessTokenValiditySeconds: 300
        refreshTokenValiditySeconds: 600

      - clientId: online-learning-mobile
        password: 5678
        accessTokenValiditySeconds: 300
        refreshTokenValiditySeconds: 600