spring:
  application:
    name: gateway-service

server:
  port: 8082

zuul:
  routes:
    online-service:
      path: /online-service/**
      serviceId: online-service
      stripPrefix: false
      sensitive-headers:


hystrix:
  command:
    online-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    region: default
    registryFetchIntervalInSeconds: 5
  instance:
    preferIpAddress: true