spring:
  application:
    name: gateway-service

server:
  port: 8082

zuul:
  routes:
    online-service:
      path: /online-service/**
      url: http://localhost:8081

hystrix:
  command:
    online-service:
      execution:
        isolation:
          thread:
            timeOutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true