spring:
  application:
    name: online-service
  data:
    mongodb:
      host: localhost
      database: online-db
      port: 27017

server:
  port: 8081
  servlet:
    context-path: /online-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    region: default
    registryFetchIntervalInSeconds: 5
  instance:
    preferIpAddress: true